# docker-compose.yml (Final Base Version for Git)

services:
  app:
    # By default, we build the image from the local source code.
    build: ./src
    # We mount the source code for live-reloading during development.
    volumes:
      - ./src:/app
      - static_volume:/app/staticfiles
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default

  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  static_volume:

networks:
  default: {}
