# docker-compose.yml
# FINAL PRODUCTION VERSION

services:
  app:
    # This is the key change:
    # Instead of building locally, we now pull the pre-built image from our registry.
    image: ghcr.io/jardahrazdera/portfolio-jaroslav-tech:latest
    restart: always # Use 'always' for production services
    volumes:
      # We no longer mount the source code, the code is inside the image.
      # We only mount the volume for static files.
      - static_volume:/app/staticfiles
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default
      - proxy

  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  static_volume:

networks:
  default: {}
  proxy:
    external: true