# docker-compose.yml (Final Base Version for Git)

services:
  app:
    image: ghcr.io/jardahrazdera/portfolio-jaroslav-tech:latest
    restart: always
    env_file: .env
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default
      - proxy
    labels:
      - "traefik.enable=true"
      # HTTP Router (for redirection) - CORRECTED SYNTAX
      - "traefik.http.routers.jaroslavtech.rule=Host(`jaroslav.tech`) || Host(`www.jaroslav.tech`)"
      - "traefik.http.routers.jaroslavtech.entrypoints=web"
      - "traefik.http.routers.jaroslavtech.middlewares=https-redirect@file"
      # HTTPS Router - CORRECTED SYNTAX
      - "traefik.http.routers.jaroslavtech-secure.rule=Host(`jaroslav.tech`) || Host(`www.jaroslav.tech`)"
      - "traefik.http.routers.jaroslavtech-secure.entrypoints=websecure"
      - "traefik.http.routers.jaroslavtech-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.jaroslavtech.loadbalancer.server.port=8000"

  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  static_volume:

networks:
  default: {}
  proxy:
    external: true
