# docker-compose.yml (Final Base Version for Git)

services:
  app:
    # The 'build' context is defined here, as it's needed for local dev.
    # The production override will ignore this and use a specific 'image'.
    build: ./src
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default

  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  static_volume:

networks:
  default: {}