# docker-compose.yml

services:
  app:
    image: ghcr.io/jardahrazdera/portfolio-jaroslav-tech:latest
    restart: always
    volumes:
      - static_volume:/app/staticfiles
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default
      - proxy
  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
  static_volume:
networks:
  default: {}
  proxy:
    external: true
