# docker-compose.yml
# Base configuration for both production and local development
# This version includes a healthcheck to ensure the database is ready before the app starts.

services:
  app:
    build: ./src
    volumes:
      - ./src:/app
      - static_volume:/app/staticfiles
    env_file:
      - .env
    # This condition tells the 'app' to wait until the 'db' service is 'healthy'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default
      - proxy

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - default
    # This section defines how to check if the database is ready
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  static_volume:

networks:
  default: {}
  proxy:
    external: true
