# Generated by Django 5.2.4 on 2025-09-21 08:05

import blog.file_utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Upload a document, archive, or code file to attach to this blog post', upload_to=blog.file_utils.generate_file_path, validators=[blog.file_utils.FileValidator()])),
                ('title', models.CharField(blank=True, help_text='Display title for the file (defaults to filename)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description of the file contents')),
                ('is_public', models.BooleanField(default=True, help_text='Whether this file is publicly downloadable')),
                ('download_count', models.PositiveIntegerField(default=0, help_text='Number of times this file has been downloaded')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='blog.post')),
            ],
            options={
                'verbose_name': 'Blog File',
                'verbose_name_plural': 'Blog Files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
