# Generated by Django 5.2.4 on 2025-09-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description (max 155 characters, will fall back to excerpt if empty)', max_length=155),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='SEO keywords, comma-separated (will auto-generate from tags if empty)', max_length=255),
        ),
    ]
