# Generated by Django 5.2.4 on 2025-09-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_meta_description_post_meta_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='discussion_url',
            field=models.URLField(blank=True, help_text='Link to external discussion (Twitter thread, LinkedIn post, Reddit discussion, etc.)', max_length=500),
        ),
    ]
