# Generated by Django 5.2.4 on 2025-09-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_add_discussion_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='share_count_facebook',
            field=models.PositiveIntegerField(default=0, help_text='Number of Facebook shares'),
        ),
        migrations.AddField(
            model_name='post',
            name='share_count_linkedin',
            field=models.PositiveIntegerField(default=0, help_text='Number of LinkedIn shares'),
        ),
        migrations.AddField(
            model_name='post',
            name='share_count_reddit',
            field=models.PositiveIntegerField(default=0, help_text='Number of Reddit shares'),
        ),
        migrations.AddField(
            model_name='post',
            name='share_count_twitter',
            field=models.PositiveIntegerField(default=0, help_text='Number of Twitter shares'),
        ),
        migrations.AddField(
            model_name='post',
            name='total_shares',
            field=models.PositiveIntegerField(default=0, help_text='Total number of shares across all platforms'),
        ),
    ]
