# Generated by Django 5.2.4 on 2025-09-23 21:28

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_add_sharing_analytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Subscriber email address', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('is_active', models.BooleanField(default=False, help_text='Whether the subscription is active (confirmed)')),
                ('is_confirmed', models.BooleanField(default=False, help_text='Whether the email has been confirmed via double opt-in')),
                ('confirmation_token', models.UUIDField(default=uuid.uuid4, help_text='Unique token for email confirmation', unique=True)),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, help_text='Unique token for unsubscribing', unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, help_text='When the subscription was first created')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When the email was confirmed', null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, help_text='When the subscription was cancelled', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address when subscribed (for compliance tracking)', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent when subscribed (for compliance tracking)')),
                ('source', models.CharField(default='website', help_text='Where the subscription came from (website, sidebar, post, etc.)', max_length=100)),
            ],
            options={
                'verbose_name': 'Newsletter Subscription',
                'verbose_name_plural': 'Newsletter Subscriptions',
                'ordering': ['-subscribed_at'],
                'indexes': [models.Index(fields=['email'], name='blog_newsle_email_581e4d_idx'), models.Index(fields=['is_active', 'is_confirmed'], name='blog_newsle_is_acti_70b793_idx'), models.Index(fields=['confirmation_token'], name='blog_newsle_confirm_9cd596_idx'), models.Index(fields=['unsubscribe_token'], name='blog_newsle_unsubsc_529478_idx')],
            },
        ),
    ]
