# Generated by Django 5.2.4 on 2025-09-25 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the view occurred')),
                ('reading_time_seconds', models.PositiveIntegerField(blank=True, help_text='How long user spent reading (seconds) - tracked via JavaScript', null=True)),
                ('completed_reading', models.BooleanField(default=False, help_text='Whether user scrolled to end of article')),
                ('user_agent_hash', models.CharField(blank=True, db_index=True, help_text='Hashed user agent for bot detection (no personal data stored)', max_length=64, null=True)),
                ('referrer_domain', models.CharField(blank=True, help_text='Domain of referring site (no full URLs stored)', max_length=100, null=True)),
                ('session_hash', models.CharField(blank=True, db_index=True, help_text='Anonymized session identifier for duplicate view prevention', max_length=64, null=True)),
                ('post', models.ForeignKey(help_text='Post being viewed', on_delete=django.db.models.deletion.CASCADE, related_name='views', to='blog.post')),
            ],
            options={
                'verbose_name': 'Post View',
                'verbose_name_plural': 'Post Views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['post', '-viewed_at'], name='blog_postvi_post_id_6afb2c_idx'), models.Index(fields=['-viewed_at'], name='blog_postvi_viewed__c6d1b4_idx'), models.Index(fields=['post', 'session_hash'], name='blog_postvi_post_id_bba8fb_idx')],
            },
        ),
    ]
