# Generated by Django 5.2.4 on 2025-08-12 16:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_alter_userprofile_bio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Brief, descriptive title for the task', max_length=200, verbose_name='Task Title')),
                ('description', models.TextField(blank=True, help_text='Detailed description of what needs to be done', verbose_name='Description')),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('review', 'In Review'), ('testing', 'Testing'), ('done', 'Done'), ('blocked', 'Blocked'), ('cancelled', 'Cancelled')], default='todo', help_text='Current status of the task', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Task priority level', max_length=10, verbose_name='Priority')),
                ('task_type', models.CharField(choices=[('feature', 'Feature'), ('bug', 'Bug Fix'), ('improvement', 'Improvement'), ('documentation', 'Documentation'), ('testing', 'Testing'), ('research', 'Research'), ('maintenance', 'Maintenance')], default='feature', help_text='Type/category of the task', max_length=20, verbose_name='Type')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated time to complete this task', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Estimated Hours')),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0.0, help_text='Actual time spent on this task', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Actual Hours')),
                ('due_date', models.DateField(blank=True, help_text='When this task should be completed', null=True, verbose_name='Due Date')),
                ('start_date', models.DateField(blank=True, help_text='When work on this task should begin', null=True, verbose_name='Start Date')),
                ('completed_date', models.DateTimeField(blank=True, help_text='When this task was completed', null=True, verbose_name='Completed Date')),
                ('progress_percentage', models.IntegerField(default=0, help_text='Task completion percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progress %')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for categorization', max_length=500, verbose_name='Tags')),
                ('external_url', models.URLField(blank=True, help_text='Link to external resource related to this task', verbose_name='External URL')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments about this task', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('assignee', models.ForeignKey(blank=True, help_text='User responsible for completing this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Assignee')),
                ('creator', models.ForeignKey(help_text='User who created this task', on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('dependencies', models.ManyToManyField(blank=True, help_text='Tasks that must be completed before this task can start', related_name='dependent_tasks', to='tasks.task', verbose_name='Dependencies')),
                ('parent_task', models.ForeignKey(blank=True, help_text='Parent task if this is a subtask', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.task', verbose_name='Parent Task')),
                ('project', models.ForeignKey(help_text='Project this task belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Comment content', verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'Task Comment',
                'verbose_name_plural': 'Task Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status'], name='tasks_task_project_b78682_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee', 'status'], name='tasks_task_assigne_7928f6_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='tasks_task_due_dat_bce847_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority', 'status'], name='tasks_task_priorit_685c61_idx'),
        ),
    ]
