# Generated by Django 5.2.4 on 2025-08-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtracker', '0003_alter_project_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_admin_approval', models.BooleanField(default=True, help_text='If enabled, new user registrations will be created as inactive and require admin approval.', verbose_name='Require Admin Approval for New Users')),
                ('enable_recaptcha', models.BooleanField(default=True, help_text='Enable reCAPTCHA protection for registration form.', verbose_name='Enable reCAPTCHA Protection')),
                ('registration_enabled', models.BooleanField(default=True, help_text='Allow new user registrations. If disabled, the registration page will be unavailable.', verbose_name='Registration Enabled')),
                ('welcome_message', models.TextField(blank=True, help_text='Optional message shown to users after successful registration (before approval).', verbose_name='Post-Registration Message')),
            ],
            options={
                'verbose_name': 'Tracker Settings',
                'verbose_name_plural': 'Tracker Settings',
            },
        ),
    ]
