# Generated by Django 5.2.4 on 2025-08-11 15:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the technology (e.g., Django, React, PostgreSQL)', max_length=100, unique=True, verbose_name='Technology Name')),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('devops', 'DevOps'), ('mobile', 'Mobile'), ('other', 'Other')], default='other', help_text='Category of technology', max_length=50, verbose_name='Category')),
                ('description', models.TextField(blank=True, help_text='Brief description of the technology', verbose_name='Description')),
                ('icon_url', models.URLField(blank=True, help_text='URL to technology icon/logo', verbose_name='Icon URL')),
                ('official_url', models.URLField(blank=True, help_text='Link to official technology website', verbose_name='Official URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the project', max_length=200, verbose_name='Project Title')),
                ('description', models.TextField(help_text='Detailed description of the project', verbose_name='Description')),
                ('short_description', models.CharField(help_text='Brief summary for project listings', max_length=300, verbose_name='Short Description')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('development', 'Development'), ('testing', 'Testing'), ('completed', 'Completed'), ('archived', 'Archived')], default='planning', help_text='Current status of the project', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Project priority level', max_length=10, verbose_name='Priority')),
                ('start_date', models.DateField(blank=True, help_text='When the project started', null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, help_text='When the project was completed', null=True, verbose_name='End Date')),
                ('github_url', models.URLField(blank=True, help_text='Link to project repository', verbose_name='GitHub URL')),
                ('live_url', models.URLField(blank=True, help_text='Link to live project demo', verbose_name='Live Demo URL')),
                ('is_featured', models.BooleanField(default=False, help_text='Display this project prominently on portfolio', verbose_name='Featured Project')),
                ('is_public', models.BooleanField(default=True, help_text='Show this project in public portfolio', verbose_name='Public Project')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('owner', models.ForeignKey(help_text='User who owns this project', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Project Owner')),
                ('technologies', models.ManyToManyField(blank=True, help_text='Technologies used in this project', related_name='projects', to='projects.technology', verbose_name='Technologies')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Project screenshot or image', upload_to='projects/images/', verbose_name='Image')),
                ('title', models.CharField(blank=True, help_text='Title or caption for the image', max_length=200, verbose_name='Image Title')),
                ('description', models.TextField(blank=True, help_text='Description of what the image shows', verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for displaying images (lower numbers first)', verbose_name='Order')),
                ('is_featured', models.BooleanField(default=False, help_text='Use as main project image', verbose_name='Featured Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('project', models.ForeignKey(help_text='Project this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project Image',
                'verbose_name_plural': 'Project Images',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Short biography or professional summary', verbose_name='Biography')),
                ('github_url', models.URLField(blank=True, help_text='Link to GitHub profile', verbose_name='GitHub URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='Link to LinkedIn profile', verbose_name='LinkedIn URL')),
                ('portfolio_url', models.URLField(blank=True, help_text='Link to personal portfolio website', verbose_name='Portfolio URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.OneToOneField(help_text='Associated Django user account', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief title describing what was worked on', max_length=200, verbose_name='Session Title')),
                ('description', models.TextField(blank=True, help_text='Detailed description of work done in this session', verbose_name='Description')),
                ('start_time', models.DateTimeField(help_text='When the work session started', verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, help_text='When the work session ended', null=True, verbose_name='End Time')),
                ('duration_hours', models.DecimalField(decimal_places=2, default=0.0, help_text='Duration of work session in hours', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Duration (Hours)')),
                ('productivity_rating', models.IntegerField(blank=True, help_text='Rate productivity from 1 (low) to 5 (high)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Productivity Rating')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or observations', verbose_name='Notes')),
                ('is_active', models.BooleanField(default=False, help_text='Is this session currently active?', verbose_name='Active Session')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('project', models.ForeignKey(help_text='Project this session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to='projects.project', verbose_name='Project')),
                ('user', models.ForeignKey(help_text='User who worked in this session', on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Work Session',
                'verbose_name_plural': 'Work Sessions',
                'ordering': ['-start_time'],
            },
        ),
    ]
