# Generated by Django 5.2.4 on 2025-08-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Short biography or professional summary (max 1000 characters)', max_length=1000, verbose_name='Biography'),
        ),
    ]
