# .github/workflows/deploy.yml
# Final version using multiple compose files

name: Build and Deploy to Server
on:
  push:
    branches: [ "main" ]
env:
  IMAGE_NAME: ghcr.io/jardahrazdera/portfolio-jaroslav-tech

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # ... (kroky checkout, login, build and push zůstávají stejné) ...

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/stacks/3-apps/jaroslav.tech
            git pull origin main

            # Login to GHCR on the server
            echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

            # === THIS IS THE KEY CHANGE ===
            # Use both the base and the production override file
            # This command will pull the new image specified in docker-compose.prod.yml
            # and restart the service.
            docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --no-deps app
