# .github/workflows/deploy.yml
# Final version using multiple compose files
name: Build and Deploy to Server
on:
  push:
    branches: [ "main" ]
env:
  IMAGE_NAME: ghcr.io/jardahrazdera/portfolio-jaroslav-tech

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
          build-args: |
            CACHEBUST=${{ github.run_number }}
            GIT_COMMIT=${{ github.sha }}

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/stacks/3-apps/jaroslav.tech
            git pull origin main
          
            echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
          
            # Stop the app container
            docker compose -f docker-compose.yml stop app
          
            # Clear the static files volume to force fresh static files
            docker volume rm jaroslavtech_static_volume || true
          
            # Pull new image and recreate
            docker compose -f docker-compose.yml pull app
            docker compose -f docker-compose.yml down app
            docker volume rm jaroslavtech_static_volume || true
            docker compose -f docker-compose.yml up -d --no-deps app
          
            # Run database migrations
            docker compose -f docker-compose.yml run --rm app python manage.py migrate --no-input
