# .github/workflows/deploy.yml
# Final, corrected version with 'git pull' step

name: Build and Deploy to Server

on:
  push:
    branches: [ "main" ]

env:
  # Nahraď 'jardahrazdera' svým GitHub jménem, pokud je jiné
  IMAGE_NAME: ghcr.io/jardahrazdera/portfolio-jaroslav-tech

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./src # Build from the 'src' subdirectory
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to the project directory on the server
            cd /opt/stacks/3-apps/jaroslav.tech

            # Pull the latest source code changes from GitHub
            git pull origin main

            # Now, pull the new Docker image that was just built
            docker compose pull app

            # And finally, restart the application container
            docker compose up -d --no-deps app
