# .github/workflows/deploy.yml
# Final version using multiple compose files
name: Build and Deploy to Server
on:
  push:
    branches: [ "main" ]
env:
  IMAGE_NAME: ghcr.io/jardahrazdera/portfolio-jaroslav-tech

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./src
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/stacks/3-apps/jaroslav.tech
            git pull origin main
          
            echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
          
            # Run database migrations first
            docker compose exec app python manage.py migrate --no-input
          
            # THEN, compile translation files
            docker compose exec app python manage.py compilemessages
          
            # AND FINALLY, collect static files
            docker compose exec app python manage.py collectstatic --no-input --clear
