# .github/workflows/django-ci.yml

name: Django CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 6 * * *'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Create .env file
        run: |
          echo "POSTGRES_DB=testdb" > .env
          echo "POSTGRES_USER=testuser" >> .env
          echo "POSTGRES_PASSWORD=testpass" >> .env
          echo "SECRET_KEY=dummy-secret-key-for-ci" >> .env
          echo "DEBUG=True" >> .env
          echo "ALLOWED_HOSTS=*" >> .env
          echo "DATABASE_URL=postgres://testuser:testpass@db:5432/testdb" >> .env

      - name: Build and Run Tests with Docker Compose
        run: |
          docker compose up --build -d
          docker compose exec app python manage.py test