# .github/workflows/django-ci.yml

name: Django CI/CD

on:
  push:
    branches: [ "main" ]
  
  pull_request:
    branches: [ "main" ]

  schedule:
    - cron: '0 6 * * *'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Build and Run Tests with Docker Compose
        run: |
          docker compose up --build --no-start
          docker compose exec app python manage.py test
      
      - name: Notify on failure
        if: failure()
        run: echo "🔴 Tests failed! Check the logs for details."